name: Web & API Automation Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # download repo
    - uses: actions/checkout@v3

    # setup java
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # install browser    
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.4.0

    # setup gradlew
    - name: Setup gradlew
      run: chmod +x gradlew

    # Execite gradle command for running cucumber test
    - name: Execute Test
      run: ./gradlew apiTest
      run: ./gradlew webTest
